<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.22">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Simulation Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-cd7454b418030687c631a6a7286fbe16.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Simulation Challenge</h1>
<p class="subtitle lead">Generative Models and Monte Carlo Simulation</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="simulation-challenge---monte-carlo-analysis" class="level1">
<h1>🎲 Simulation Challenge - Monte Carlo Analysis</h1>
<section id="challenge-overview" class="level2">
<h2 class="anchored" data-anchor-id="challenge-overview">Challenge Overview</h2>
<p><strong>Your Mission:</strong> Create a comprehensive Quarto document that simulates one or two investment strategies, analyzes the results, and demonstrates your ability to present counter-intuitive findings compellingly. Then render the document to HTML and deploy it via GitHub Pages from a new repository called “simulationChallenge.”</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>⚠️ AI Partnership Required
</div>
</div>
<div class="callout-body-container callout-body">
<p>This challenge pushes boundaries intentionally. You’ll tackle problems that normally require weeks of study, but with Cursor AI as your partner (and your brain keeping it honest), you can accomplish more than you thought possible.</p>
<p><strong>The new reality:</strong> The four stages of competence are Ignorance → Awareness → Learning → Mastery. AI lets us produce Mastery-level work while operating primarily in the Awareness stage. I focus on awareness training, you leverage AI for execution, and together we create outputs that used to require years of dedicated study.</p>
</div>
</div>
</section>
<section id="the-investment-game" class="level2">
<h2 class="anchored" data-anchor-id="the-investment-game">The Investment Game 🎯</h2>
<section id="original-game-strategy" class="level3">
<h3 class="anchored" data-anchor-id="original-game-strategy">Original Game Strategy</h3>
<div id="exm-ErgodicityEconomicsExample" class="theorem example">
<p><span class="theorem-title"><strong>Example 1</strong></span> Imagine you are offered the following game and given a $1,000 budget in a special account to play the game: I will flip a coin, and if it comes up heads, we increase your account’s balance by 50%; if it comes up tails, we reduce your account’s balance by 40%. We are not only doing this once, but we will do it once per year until you turn 55. When you turn 55, you will receive the balance in your account.</p>
</div>
</section>
</section>
<section id="challenge-requirements" class="level2">
<h2 class="anchored" data-anchor-id="challenge-requirements">Challenge Requirements 📋</h2>
<section id="minimum-requirements-for-any-points-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="minimum-requirements-for-any-points-on-challenge">Minimum Requirements for Any Points on Challenge</h3>
<ol type="1">
<li><p><strong>Create a Quarto Document:</strong> Write a concise quarto markdown file that includes a narrative of what you are doing along with the requested code, results, and visualizations of your simulations.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>💡 Pro Tip: Source File Reference
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Need help with Quarto syntax or DAFT diagrams?</strong> You can find the complete source <code>.qmd</code> file for this challenge at:</p>
<p><strong>GitHub Repository:</strong> <a href="https://github.com/flyaflya/buad442Fall2025/blob/main/challenges/03-Simulation-Challenge/simulationChallenge.qmd">flyaflya/buad442Fall2025/challenges/03-Simulation-Challenge/simulationChallenge.qmd</a></p>
<p>This is a great resource for understanding Quarto syntax, seeing how DAFT diagrams are implemented, and learning from the complete working example!</p>
</div>
</div></li>
<li><p><strong>Render to HTML:</strong> You must render the quarto markdown file to HTML.</p></li>
<li><p><strong>GitHub Repository:</strong> The rendered HTML must be uploaded to a new GitHub repository called “simulationChallenge” in your Github account.</p></li>
<li><p><strong>GitHub Pages Setup:</strong> The repository should be made the source of your github pages:</p>
<ul>
<li>Go to your repository settings (click the “Settings” tab in your GitHub repository)</li>
<li>Scroll down to the “Pages” section in the left sidebar</li>
<li>Under “Source”, select “Deploy from a branch”</li>
<li>Choose “main” branch and “/ (root)” folder</li>
<li>Click “Save”</li>
<li>Your site will be available at: <code>https://[your-username].github.io/simulationChallenge/</code></li>
<li><strong>Note:</strong> It may take a few minutes for the site to become available after enabling Pages</li>
</ul></li>
</ol>
</section>
</section>
<section id="grading-rubric" class="level2">
<h2 class="anchored" data-anchor-id="grading-rubric">Grading Rubric 🎓</h2>
<section id="questions-to-answer-for-75-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-75-grade-on-challenge">Questions to Answer for 75% Grade on Challenge</h3>
<ol type="1">
<li><p><strong>Expected Value Analysis:</strong> What is the “expected value” of your account balance after 1 coin flip for the original game?</p></li>
<li><p><strong>Expectation vs.&nbsp;Reality:</strong> Is the expected value positive or negative? Do you expect your account to be worth more or less than $1,000 based on this result?</p></li>
<li><p><strong>Single Simulation:</strong> Run one simulation showing the dynamics of your account balance over time. Make an object-oriented matplotlib OR ggplot2 plot showing your simulated account balance over time (i.e.&nbsp;as you age). Comment on the results, are you happy?</p></li>
</ol>
</section>
<section id="questions-to-answer-for-85-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-85-grade-on-challenge">Questions to Answer for 85% Grade on Challenge</h3>
<ol start="4" type="1">
<li><strong>Multiple Simulations:</strong> Run 100 simulations modelling the dynamics of your account balance over time. Make an object-oriented matplotlib OR ggplot2 plot showing a probability distribution of the 100 simulatedaccount balance at age 55. Comment on the results, are you happy? Why or why not?</li>
</ol>
</section>
<section id="questions-to-answer-for-95-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-95-grade-on-challenge">Questions to Answer for 95% Grade on Challenge</h3>
<ol start="5" type="1">
<li><strong>Probability Analysis:</strong> Based on the 100 simulations above, what is the probability that your account balance will be greater than $1,000 at age 55?</li>
</ol>
</section>
<section id="questions-to-answer-for-100-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-100-grade-on-challenge">Questions to Answer for 100% Grade on Challenge</h3>
<ol start="6" type="1">
<li><strong>Strategy Comparison:</strong> Run 100 simulations for the modified game strategy shown below in <a href="#exm-ErgodicityEconomicsExampleModified" class="quarto-xref">Example&nbsp;2</a>. What is the probability that your account balance will be greater than $10,000 at age 55? Is this probability higher or lower than the probability in the original game?</li>
</ol>
</section>
<section id="modified-game-strategy" class="level3">
<h3 class="anchored" data-anchor-id="modified-game-strategy">Modified Game Strategy</h3>
<div id="exm-ErgodicityEconomicsExampleModified" class="theorem example">
<p><span class="theorem-title"><strong>Example 2</strong></span> Imagine you are offered the following game and given a $1,000 budget in a special account to play the game: I will flip a coin, and if it comes up heads, we increase your bet by 50%; if it comes up tails, we reduce your bet by 40%. You must bet exactly 50% of your current account balance on each flip, and this 50% is locked in for each round. We are not only doing this once, but we will do it once per year until you turn 55. When you turn 55, you will receive the balance in your account.</p>
</div>
</section>
</section>
<section id="technical-implementation-preferences" class="level2">
<h2 class="anchored" data-anchor-id="technical-implementation-preferences">Technical Implementation Preferences 💡</h2>
<section id="setting-up-your-analysis" class="level3">
<h3 class="anchored" data-anchor-id="setting-up-your-analysis">Setting Up Your Analysis</h3>
<p><strong>For R Users:</strong></p>
<ul>
<li>Use <code>tidyverse</code> for data manipulation</li>
<li>Use <code>ggplot2</code> for visualizations</li>
<li>Use <code>set.seed()</code> for reproducible results</li>
</ul>
<p><strong>For Python Users:</strong></p>
<ul>
<li>Use <code>numpy</code> for numerical operations</li>
<li>Use <code>pandas</code> for data manipulation</li>
<li>Use <code>matplotlib</code> (object-oriented)</li>
<li>Use <code>np.random.seed()</code> for reproducible results</li>
</ul>
</section>
<section id="visualization-preferences" class="level3">
<h3 class="anchored" data-anchor-id="visualization-preferences">Visualization Preferences</h3>
<ul>
<li><strong>Professional Styling:</strong> Use consistent colors, clear labels, readable fonts, and informative titles</li>
</ul>
</section>
</section>
<section id="submission-checklist" class="level2">
<h2 class="anchored" data-anchor-id="submission-checklist">Submission Checklist ✅</h2>
<p><strong>Minimum Requirements (Required for Any Points):</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Quarto document created with clear narrative</label></li>
<li><label><input type="checkbox">Document rendered to HTML successfully</label></li>
<li><label><input type="checkbox">Repository “simulationChallenge” created</label></li>
<li><label><input type="checkbox">HTML files uploaded to repository</label></li>
<li><label><input type="checkbox">GitHub Pages enabled and working</label></li>
<li><label><input type="checkbox">Site accessible at <code>https://[your-username].github.io/simulationChallenge/</code></label></li>
</ul>
<p><strong>75% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Expected value calculations shown (Question 1)</label></li>
<li><label><input type="checkbox">Expectation vs.&nbsp;reality analysis (Question 2)</label></li>
<li><label><input type="checkbox">Single simulation with time series plot (Question 3)</label></li>
<li><label><input type="checkbox">Clear interpretation of single simulation results</label></li>
</ul>
<p><strong>85% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">100 simulations with distribution analysis (Question 4)</label></li>
<li><label><input type="checkbox">Probability distribution plot of final account balances</label></li>
<li><label><input type="checkbox">Clear interpretation of multiple simulation results</label></li>
</ul>
<p><strong>95% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Probability calculations for original strategy (Question 5)</label></li>
<li><label><input type="checkbox">Analysis of probability that balance &gt; $1,000 at age 55</label></li>
</ul>
<p><strong>100% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">100 simulations for modified strategy (Question 6)</label></li>
<li><label><input type="checkbox">Probability calculations for modified strategy</label></li>
<li><label><input type="checkbox">Comparative analysis between both strategies</label></li>
<li><label><input type="checkbox">Analysis of probability that balance &gt; $10,000 at age 55</label></li>
</ul>
<p><strong>Code Quality (All Grades):</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Reproducible results (seeds set)</label></li>
<li><label><input type="checkbox">Clean, well-commented code</label></li>
<li><label><input type="checkbox">Appropriate use of functions and loops</label></li>
<li><label><input type="checkbox">Professional visualization styling</label></li>
</ul>
<section id="resources" class="level3">
<h3 class="anchored" data-anchor-id="resources">Resources</h3>
<ul>
<li><strong>Quarto Markdown:</strong> <a href="https://quarto.org/docs/authoring/markdown-basics.html">quarto.org/docs/authoring/markdown-basics.html</a></li>
<li><strong>Quarto Documentation:</strong> <a href="https://quarto.org/docs">quarto.org/docs</a></li>
<li><strong>R for Data Science:</strong> <a href="https://r4ds.had.co.nz">r4ds.had.co.nz</a></li>
<li><strong>Python Data Science Handbook:</strong> <a href="https://jakevdp.github.io/PythonDataScienceHandbook">jakevdp.github.io/PythonDataScienceHandbook</a></li>
</ul>
</section>
<section id="getting-started-tips" class="level3">
<h3 class="anchored" data-anchor-id="getting-started-tips">Getting Started Tips</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>🎯 Navy SEALs Motto
</div>
</div>
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p>“Slow is Smooth and Smooth is Fast”</p>
</blockquote>
<p><em>Take your time to understand the simulation mechanics, plan your approach carefully, and execute with precision. Rushing through this challenge will only lead to errors and confusion.</em></p>
</div>
</div>
<ul>
<li><strong>Browse <a href="@sec-simulation-concepts">Essential Simulation Concepts</a>:</strong> This section will give you a good understanding of the concepts you need to know to complete the challenge.</li>
<li><strong>Start Simple:</strong> Begin with a single simulation to understand the mechanics</li>
<li><strong>Document Everything:</strong> Explain your reasoning and interpret your results</li>
<li><strong>Forgetting to Set Seeds:</strong> Always set random seeds for reproducible results</li>
<li><strong>Total time to complete:</strong> ~3-4 hours for the 100% grade ⏱️</li>
<li><strong>Good luck, and remember simulation will steer you right even when intuition will steer you wrong!</strong> 🎲</li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>💾 Important: Save Your Work Frequently!
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Before you start coding:</strong> Make sure to commit your work often using the Source Control panel in Cursor (Ctrl+Shift+G or Cmd+Shift+G). This prevents the AI from overwriting your progress and ensures you don’t lose your work.</p>
<p><strong>Commit after each major step:</strong></p>
<ul>
<li>After completing each simulation example</li>
<li>After finishing each challenge question</li>
<li>Before asking the AI for help with new code</li>
</ul>
<p><strong>How to commit:</strong></p>
<ol type="1">
<li>Open Source Control panel (Ctrl+Shift+G)</li>
<li>Stage your changes (+ button)</li>
<li>Write a descriptive commit message</li>
<li>Click the checkmark to commit</li>
</ol>
<p><em>Remember: Frequent commits are your safety net!</em></p>
</div>
</div>
</section>
</section>
</section>
<section id="my-analysis-investment-game-simulation" class="level1">
<h1>My Analysis: Investment Game Simulation 🎯</h1>
<p>Now let’s work through the challenge questions step by step, implementing the actual simulations and analysis.</p>
<section id="question-1-expected-value-after-1-coin-flip" class="level2">
<h2 class="anchored" data-anchor-id="question-1-expected-value-after-1-coin-flip">Question 1: Expected Value After 1 Coin Flip</h2>
<p><strong>Answer:</strong> The expected value is <strong>$1,050</strong></p>
<p><strong>Calculation:</strong> - Heads (50% chance): $1,000 × 1.5 = $1,500 - Tails (50% chance): $1,000 × 0.6 = $600 - Expected Value = 0.5 × $1,500 + 0.5 × $600 = <strong>$1,050</strong></p>
</section>
<section id="question-2-expectation-vs.-reality" class="level2">
<h2 class="anchored" data-anchor-id="question-2-expectation-vs.-reality">Question 2: Expectation vs.&nbsp;Reality</h2>
<p><strong>Answer:</strong> The expected value is <strong>positive</strong> ($1,050 vs.&nbsp;$1,000), so we expect the account to be worth <strong>more</strong> than $1,000.</p>
<p><strong>However:</strong> This is just math! In reality, you’ll either get $1,500 or $600 - the expected value doesn’t guarantee anything.</p>
</section>
<section id="question-3-single-simulation-over-time" class="level2">
<h2 class="anchored" data-anchor-id="question-3-single-simulation-over-time">Question 3: Single Simulation Over Time</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>R Version: R version 4.4.2 (2024-10-31 ucrt) </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>R Platform: x86_64-w64-mingw32 </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/single-simulation-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>One simulation showing account balance from age 25 to 55</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Final Balance at Age 55: $ 8042.62 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Total Return:  704.3 %</code></pre>
</div>
</div>
<p><strong>Answer:</strong> In this single simulation, the final balance was <strong>$8042.62</strong> with a <strong>704.3%</strong> return.</p>
<p><strong>Am I happy?</strong> Based on this result, I am <strong>[happy/surprised]</strong> because the simulation shows <strong>[a significant gain/loss]</strong> over 30 years.</p>
</section>
<section id="question-4-100-simulations---distribution-of-results" class="level2">
<h2 class="anchored" data-anchor-id="question-4-100-simulations---distribution-of-results">Question 4: 100 Simulations - Distribution of Results</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/multiple-simulations-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Distribution of final balances from 100 simulations</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Results from 100 simulations:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean final balance: $ 1782.22 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Median final balance: $ 205.89 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Probability above $1,000:  28 %</code></pre>
</div>
</div>
<p><strong>Answer:</strong> From 100 simulations: - <strong>Mean final balance:</strong> $1782.22 - <strong>Median final balance:</strong> $205.89<br>
- <strong>Probability above $1,000:</strong> 28%</p>
<p><strong>Am I happy?</strong> Based on these results, I am <strong>[surprised/concerned]</strong> because most simulations show <strong>[gains/losses]</strong> despite the positive expected value per flip.</p>
</section>
<section id="question-5-probability-of-ending-up-above-1000" class="level2">
<h2 class="anchored" data-anchor-id="question-5-probability-of-ending-up-above-1000">Question 5: Probability of Ending Up Above $1,000</h2>
<p><strong>Answer:</strong> The probability that your account balance will be greater than $1,000 at age 55 is approximately <strong>28%</strong>.</p>
<p>This is calculated from our 100 simulations above - we simply count how many simulations ended up above $1,000 and divide by 100.</p>
<p><strong>Key Insight:</strong> Even though each coin flip has a positive expected value, most people actually lose money over 30 years! This is the counterintuitive result of the investment game.</p>
</section>
<section id="question-6-modified-game-strategy-comparison" class="level2">
<h2 class="anchored" data-anchor-id="question-6-modified-game-strategy-comparison">Question 6: Modified Game Strategy Comparison</h2>
<p><strong>Modified Game Rules:</strong> - You bet exactly 50% of your current balance on each flip - Heads: You gain 25% of your current balance (1.25x multiplier) - Tails: You lose 20% of your current balance (0.80x multiplier)</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/modified-game-comparison-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Comparison of original vs modified game strategies</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Strategy Comparison Results:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Original Game - Probability above $10,000:  4 %</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Modified Game - Probability above $10,000:  2 %</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Original Game - Mean final balance: $ 1782.22 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Modified Game - Mean final balance: $ 2293.98 </code></pre>
</div>
</div>
<p><strong>Answer:</strong> - <strong>Original Game:</strong> Probability above $10,000 = <strong>4%</strong> - <strong>Modified Game:</strong> Probability above $10,000 = <strong>2%</strong></p>
<p><strong>Comparison:</strong> The probability in the modified game is <strong>LOWER</strong> than the original game.</p>
<p><strong>Why?</strong> The modified game is more conservative - smaller gains (+25% vs +50%) but also smaller losses (-20% vs -40%), which changes the risk profile.</p>
</section>
</section>
<section id="conclusion-key-insights" class="level1">
<h1>Conclusion: Key Insights 🎯</h1>
<section id="what-we-learned" class="level2">
<h2 class="anchored" data-anchor-id="what-we-learned">What We Learned</h2>
<p><strong>The Counterintuitive Truth:</strong> Even though each coin flip has a positive expected value, most people actually lose money over 30 years!</p>
<section id="key-insights" class="level3">
<h3 class="anchored" data-anchor-id="key-insights">Key Insights:</h3>
<ol type="1">
<li><strong>Expected Value ≠ Reality</strong>: Just because the math says you should make money doesn’t mean you will</li>
<li><strong>Volatility Kills Returns</strong>: High volatility (big swings) reduces your chances of success over time</li>
<li><strong>Simulation Reveals Truth</strong>: Running 100 simulations showed us what intuition couldn’t predict</li>
</ol>
</section>
<section id="why-this-happens" class="level3">
<h3 class="anchored" data-anchor-id="why-this-happens">Why This Happens:</h3>
<ul>
<li><strong>Multiplicative Process</strong>: Each loss compounds, making it harder to recover</li>
<li><strong>Asymmetric Risk</strong>: A 40% loss requires a 67% gain just to break even</li>
<li><strong>Time Amplifies Problems</strong>: Over 30 years, bad luck compounds dramatically</li>
</ul>
</section>
</section>
<section id="the-big-picture" class="level2">
<h2 class="anchored" data-anchor-id="the-big-picture">The Big Picture</h2>
<p>This challenge demonstrates why <strong>simulation is so powerful</strong> - it reveals insights that pure mathematics and intuition miss. The expected value said “you should make money,” but the simulation said “most people lose money.”</p>
<p><strong>Lesson:</strong> When making important decisions, especially about money, don’t just look at averages - understand the full range of possible outcomes through simulation.</p>
<hr>
<p><em>This analysis shows the power of computational methods in understanding complex systems where intuition alone can be misleading.</em></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>